name: evoting
description: E voting using blockchain

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.3.2

  dio: ^4.0.6
  web3dart: ^2.4.0
  http: ^0.13.4

  equatable: ^2.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1


dev_dependencies:

flutter:

  uses-material-design: true

  assets:
    - assets/
